### ISSUE TITLE
[BUG] Email doesn't show under Creator

### ISSUE THREAD

**Issue by elba3184** [Banda-Media/lunchMemo#203]
**Describe the bug**
I created a group and it successfully created with all the information I filled in, but the creator section appears empty.

**To Reproduce**
1. Go to 'Home'
2. Scroll to my created group
3. See the error of missing `Creator: email`

## Expected behavior
Expected to see my email next to 'Creator', instead was blank

### Device
- [X] MacOS Desktop

### Browser
- [X] Chrome
-

**Comment by AndresMWeber** [comment]
This was due to the registration step for creating a user's firestore entry being skipped.  Need to look into this for new user registrations.

**Comment by AndresMWeber** [comment]
This is now obsolete with the new api /api/users/profiles endpoint.  Need to revise  the implementation to use the endpoint to fix this bug which is also a two sources of truth bug anyways.
