### ISSUE TITLE
Create Group Form

### ISSUE THREAD

**Issue by elba3184** [Banda-Media/lunchMemo#204]
# Description
When creating a group, filling out the information, and pressing 'Create Group', the group is successfully created. However, the information doesn't clear out, which may not be a bad thing, but I could accidentally press 'Create Group' again and create a duplicate group without realizing it at first glance. Again, may not be a bad thing, but I think the action should be to clear out the form once the group is created.

**Comment by elba3184** [comment]
This seems to be working fine

**Comment by AndresMWeber** [comment]
Verified!
